name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Check formatting (go fmt)
        run: |
          fmt_out=$(go fmt ./...)
          if [ -n "$fmt_out" ]; then
            echo "The following files are not gofmt'd:" >&2
            echo "$fmt_out" >&2
            exit 1
          fi

      - name: Static analysis (go vet)
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: ~/go/bin/staticcheck ./...

      - name: Run tests
        run: go test -v ./...

      - name: Upload coverage report
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
        if: always()