name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Clean Go build and mod cache (before)
        run: go clean -cache -modcache

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Clean Go build and mod cache (after)
        run: go clean -cache -modcache


      - name: Check go.mod/go.sum (tidy)
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Check formatting (go fmt)
        run: |
          fmt_out=$(go fmt ./...)
          if [ -n "$fmt_out" ]; then
            echo "The following files are not gofmt'd:" >&2
            echo "$fmt_out" >&2
            exit 1
          fi

      - name: Static analysis (go vet)
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: ~/go/bin/staticcheck ./...

      - name: Run tests
        run: go test -v -race -cover ./...

      - name: Upload coverage report
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
        if: always()

  docker_build:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Docker image (local, for scan)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/taskmanager:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: List local Docker images (debug)
        run: docker images



      - name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: "image"
          image-ref: ghcr.io/${{ github.repository_owner }}/taskmanager:${{ github.sha }}
          exit-code: "1"
          severity: "CRITICAL,HIGH"
      - name: Push Docker image to registry
        run: docker push ghcr.io/${{ github.repository_owner }}/taskmanager:${{ github.sha }}
